<b>Linear Regression: </b> Fit a straight line in the data to minimize distance. Intercept and slope used to predict future outcome. 
    - Predictor Variable:      X
    - Responsive Variable:     Y
    
    
Dimensionality reduction?
- Appears to be talking physics! :D

#### Training Machine Learning:




In [5]:
from numpy import *

a = array([(1, 2, 3, 4, 5), (1, 2, 3, 4, 5)])
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [10]:
b = ones((3, 4, 5), dtype=int16) # x, y, z, type
b

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [12]:
empty((3, 3)) # x, y ...

array([[  0.00000000e+000,  -3.10503637e+231,   2.15363016e-314],
       [  2.15366289e-314,   2.15356585e-314,   2.15366305e-314],
       [  2.14442225e-314,   0.00000000e+000,   2.13533252e-314]])

In [14]:
arange(0, 4, 1.2) # from to step

array([ 0. ,  1.2,  2.4,  3.6])

In [15]:
linspace(0, 9, 25) # from to howmany

array([ 0.   ,  0.375,  0.75 ,  1.125,  1.5  ,  1.875,  2.25 ,  2.625,
        3.   ,  3.375,  3.75 ,  4.125,  4.5  ,  4.875,  5.25 ,  5.625,
        6.   ,  6.375,  6.75 ,  7.125,  7.5  ,  7.875,  8.25 ,  8.625,  9.   ])

In [23]:
print(arange(15))
print("")
print(arange(15).reshape(3, 5))
print("")
print(arange(24).reshape(2, 3, 4))

# set_printoptions(threshold='nan') Might come in handy at some point. This will force the 
# numpy arrays to print the entire thing instead of printing with elipses when the array
# is to large. 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
aa = array([20, 25, 30, 35, 40])
bb = arange(aa.size)
cc = aa - bb
print(cc)
dot(aa, bb)

[20 24 28 32 36]


350

In [33]:
arange(15).reshape(3, 5).sum(axis=0) # sum of each col
arange(15).reshape(3, 5).sum(axis=1) # sum of each row

array([10, 35, 60])

In [32]:
arange(15).reshape(3, 5).min(axis=1) # min of each row
arange(15).reshape(3, 5).min(axis=0) # min of each col

array([0, 1, 2, 3, 4])

In [35]:
araarange(15).reshape(3, 5).min(axis=0) # min of each colnge(15).reshape(3, 5).cumsum(axis=0) # min of each row
arange(15).reshape(3, 5).cumsum(axis=1) # min of each col

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [67]:
def f(x, y):
    return 10*(x+y)

zeray = fromfunction(f, (6, 5), dtype=int)
zeray # row, column

array([[ 0, 10, 20, 30, 40],
       [10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90]])

In [71]:
3 * 9 + (3*8*0.119)

zeray[:,0:2]

array([[ 0, 10],
       [10, 20],
       [20, 30],
       [30, 40],
       [40, 50],
       [50, 60]])

In [69]:
zeray[-1]

array([50, 60, 70, 80, 90])

In [73]:
for row in zeray: # done with respect to the first axis
    print(row)

[ 0 10 20 30 40]
[10 20 30 40 50]
[20 30 40 50 60]
[30 40 50 60 70]
[40 50 60 70 80]
[50 60 70 80 90]


In [76]:
for element in zeray.flat:
    print(element)

0
10
20
30
40
10
20
30
40
50
20
30
40
50
60
30
40
50
60
70
40
50
60
70
80
50
60
70
80
90


In [77]:
zeray.shape

(6, 5)

In [78]:
zeray.ravel()

array([ 0, 10, 20, 30, 40, 10, 20, 30, 40, 50, 20, 30, 40, 50, 60, 30, 40,
       50, 60, 70, 40, 50, 60, 70, 80, 50, 60, 70, 80, 90])

In [79]:
zeray.transpose()

array([[ 0, 10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50, 60],
       [20, 30, 40, 50, 60, 70],
       [30, 40, 50, 60, 70, 80],
       [40, 50, 60, 70, 80, 90]])

In [82]:
zeray.reshape((3, 10))

array([[ 0, 10, 20, 30, 40, 10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60, 30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80, 50, 60, 70, 80, 90]])

In [83]:
zeray.reshape((6, -1))

array([[ 0, 10, 20, 30, 40],
       [10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90]])

In [84]:
xeray = fromfunction(f, (6, 5), dtype=int)
xeray # row, column

array([[ 0, 10, 20, 30, 40],
       [10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90]])

In [91]:
yeray = fromfunction(f, (12, 5), dtype=int)
yeray # row, column

array([[  0,  10,  20,  30,  40],
       [ 10,  20,  30,  40,  50],
       [ 20,  30,  40,  50,  60],
       [ 30,  40,  50,  60,  70],
       [ 40,  50,  60,  70,  80],
       [ 50,  60,  70,  80,  90],
       [ 60,  70,  80,  90, 100],
       [ 70,  80,  90, 100, 110],
       [ 80,  90, 100, 110, 120],
       [ 90, 100, 110, 120, 130],
       [100, 110, 120, 130, 140],
       [110, 120, 130, 140, 150]])

In [90]:
c_ray = vstack((zeray, xeray))
c_ray

array([[ 0, 10, 20, 30, 40],
       [10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40],
       [10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90]])

In [92]:
hstack((c_ray, yeray))

array([[  0,  10,  20,  30,  40,   0,  10,  20,  30,  40],
       [ 10,  20,  30,  40,  50,  10,  20,  30,  40,  50],
       [ 20,  30,  40,  50,  60,  20,  30,  40,  50,  60],
       [ 30,  40,  50,  60,  70,  30,  40,  50,  60,  70],
       [ 40,  50,  60,  70,  80,  40,  50,  60,  70,  80],
       [ 50,  60,  70,  80,  90,  50,  60,  70,  80,  90],
       [  0,  10,  20,  30,  40,  60,  70,  80,  90, 100],
       [ 10,  20,  30,  40,  50,  70,  80,  90, 100, 110],
       [ 20,  30,  40,  50,  60,  80,  90, 100, 110, 120],
       [ 30,  40,  50,  60,  70,  90, 100, 110, 120, 130],
       [ 40,  50,  60,  70,  80, 100, 110, 120, 130, 140],
       [ 50,  60,  70,  80,  90, 110, 120, 130, 140, 150]])

In [93]:
x, y = 5, 6

def funny_matrix(xs, ys, loops):
    if loops == 0:
        return (xs, ys)
    elif loops % 2 == 0:
        return (xs, ys*2)
    else:
        return (xs*2, ys)

count = 0
while count < 10:
    count += 1
    if count % 2 == 0 and not count == 0:
        pass
# play with h stack vstack building new arrays.
# column_stack works for 1D Arrays
# row_stack does tha same with rows added to the 2d array

In [101]:
hsplit(c_ray, 5) # horizontal split
vsplit(c_ray, 3) # Vertical split

[array([[ 0, 10, 20, 30, 40],
        [10, 20, 30, 40, 50],
        [20, 30, 40, 50, 60],
        [30, 40, 50, 60, 70]]), array([[40, 50, 60, 70, 80],
        [50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40],
        [10, 20, 30, 40, 50]]), array([[20, 30, 40, 50, 60],
        [30, 40, 50, 60, 70],
        [40, 50, 60, 70, 80],
        [50, 60, 70, 80, 90]])]

In [96]:
a = floor(10*random.random((2,12)))

In [97]:
a

array([[ 9.,  0.,  2.,  2.,  9.,  8.,  0.,  6.,  3.,  0.,  7.,  3.],
       [ 1.,  2.,  0.,  1.,  2.,  3.,  7.,  1.,  3.,  1.,  7.,  0.]])

In [118]:
c = a.view() # shallow copy
print("C IS A: ",  c is a) # C is not A
print("c.flags.owndata: ", c.flags.owndata) # C doesn't own the data
c.shape = (12, -1)
print("c.shape: ", c.shape)
print("a.shape: ", a.shape) # shape doesn't change when c's shape is changed
print(a)
c[0, 1] = 123
print(c)
print(a) # C changes A...

C IS A:  False
c.flags.owndata:  False
c.shape:  (12, 2)
a.shape:  (2, 12)
[[   9.  123.    2.    2.    9.    8.    0.    6.    3.    0.    7.    3.]
 [   1.    2.    0.    1.    2.    3.    7.    1.    3.    1.    7.    0.]]
[[   9.  123.]
 [   2.    2.]
 [   9.    8.]
 [   0.    6.]
 [   3.    0.]
 [   7.    3.]
 [   1.    2.]
 [   0.    1.]
 [   2.    3.]
 [   7.    1.]
 [   3.    1.]
 [   7.    0.]]
[[   9.  123.    2.    2.    9.    8.    0.    6.    3.    0.    7.    3.]
 [   1.    2.    0.    1.    2.    3.    7.    1.    3.    1.    7.    0.]]


In [122]:
a = array([2,3,4,5])
b = array([8,5,4])
c = array([5,4,6,8,3])
ax,bx,cx = ix_(a,b,c)  # looks like this has something to do with matrices algebra. 
                        # It does some maths to the matrices, the tutorial said a + b * c
                        # not exactly the best explained, so will have to look at it in more detail. 

print(ax)
print(bx)
print(cx)

ax+bx*cx

[[[2]]

 [[3]]

 [[4]]

 [[5]]]
[[[8]
  [5]
  [4]]]
[[[5 4 6 8 3]]]


array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [123]:
def ufunc_reduce(ufct, *vectors):
    vs = ix_(*vectors)
    r = ufct.identity
    for v in vs:
        r = ufct(r,v)
    return r

In [124]:
ufunc_reduce(add,a,b,c) # ha, this looks like a nifty way of producing the same answer. 
                        # need to learn mor eon how passing and calling functions work. 
                        # Reminds me of function pointers. <3

array([[[15, 14, 16, 18, 13],
        [12, 11, 13, 15, 10],
        [11, 10, 12, 14,  9]],

       [[16, 15, 17, 19, 14],
        [13, 12, 14, 16, 11],
        [12, 11, 13, 15, 10]],

       [[17, 16, 18, 20, 15],
        [14, 13, 15, 17, 12],
        [13, 12, 14, 16, 11]],

       [[18, 17, 19, 21, 16],
        [15, 14, 16, 18, 13],
        [14, 13, 15, 17, 12]]])

In [125]:
from numpy import *
from numpy.linalg import *

a = array([[1.0, 2.0], [3.0, 4.0]])
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [126]:
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [128]:
u = eye(2) # unit 2x2 matrix; "eye" represents "I" # LOL
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [130]:
j = array([[0.0, -1.0], [1.0, 0.0]])
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [132]:
dot(j, j) # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [133]:
trace(u)  # trace

2.0

In [134]:
trace(j)  # trace does what I think it does

0.0

In [135]:
y = array([[5.], [7.]])
y

array([[ 5.],
       [ 7.]])

In [136]:
solve(a, y)

array([[-3.],
       [ 4.]])

In [137]:
eig(j) # what? Does eigen vectors? :D

(array([ 0.+1.j,  0.-1.j]),
 array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))

In [140]:
A = matrix('1.0 2.0; 3.0 4.0')
A

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [141]:
A.T

matrix([[ 1.,  3.],
        [ 2.,  4.]])

In [148]:
X = matrix('5.0 7.0')
print(X)
Y = X.T
Y

[[ 5.  7.]]


matrix([[ 5.],
        [ 7.]])

In [152]:
print(A*Y)
print(A.I)
solve(A, Y) # Solves a linear equation. 

[[ 19.]
 [ 43.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


matrix([[-3.],
        [ 4.]])

In [179]:
Q = arange(12)
print(Q)
Q.shape = (3,4)

M = mat(Q.copy())
print(type(Q),type(M))
print()
print(Q, Q.shape)
print(M, M.shape)
print("\nQ Row and Shape")
print(Q[:,1]); print(Q[:,1].shape)
print("\nM Col and Shape")
print(M[:]); print(M[:].shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'> <class 'numpy.matrixlib.defmatrix.matrix'>

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)

Q Row and Shape
[1 5 9]
(3,)

M Col and Shape
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
