In [1]:
import theano
from theano import tensor as T, function

import numpy as np



In [5]:
X = T.matrix('x')
Y = X ** 2
# T.grad calculates derivative
Z = T.grad(Y.sum(), X)
F = function([X], [Y, Z])

In [6]:
x = np.ones((2, 2)) * 3

y, z = F(x)

In [7]:
print(x)
print('-'*12)
print(y)
print('-'*12)
print(z)


[[ 3.  3.]
 [ 3.  3.]]
------------
[[ 9.  9.]
 [ 9.  9.]]
------------
[[ 6.  6.]
 [ 6.  6.]]
